import { createFileRoute, Link } from "@tanstack/react-router";
import { Heart, LayoutDashboard, LogOut, MapPin, Package, Plus, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { ProductCard } from "@/components/product-card";
import { formatBDT, products } from "@/lib/products";

export const Route=createFileRoute("/dashboard")({head:()=>({meta:[{title:"Customer Dashboard — Try Decants"},{name:"description",content:"Manage Try Decants orders, wishlist, addresses and account details."},{property:"og:title",content:"Customer Dashboard — Try Decants"},{property:"og:description",content:"Your Try Decants customer account overview."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:DashboardPage});
const tabs=[{id:"Dashboard",Icon:LayoutDashboard},{id:"My Orders",Icon:Package},{id:"Wishlist",Icon:Heart},{id:"Address Book",Icon:MapPin},{id:"Account Details",Icon:UserRound}] as const;
const orders=[{id:"#TD-1048",items:"Aventus 5ml, Khamrah 3ml",date:"12 Sep 2026",status:"Processing",total:2750},{id:"#TD-1031",items:"Bianco Latte 5ml",date:"29 Aug 2026",status:"Shipped",total:1470},{id:"#TD-0998",items:"Delina Exclusif 3ml",date:"08 Aug 2026",status:"Delivered",total:1400}];
function DashboardPage(){const [active,setActive]=useState<(typeof tabs)[number]["id"]>("Dashboard");return <div className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><p className="eyebrow">My account</p><h1 className="mt-3 font-display text-4xl">Customer Dashboard</h1><div className="mt-10 grid gap-8 lg:grid-cols-[250px_minmax(0,1fr)]"><aside className="self-start rounded-sm bg-navy p-4">{tabs.map(({id,Icon})=><button key={id} type="button" onClick={()=>setActive(id)} className={`flex w-full items-center gap-3 rounded-sm px-4 py-3 text-left text-sm ${active===id?"bg-gold text-navy":"text-ivory/75 hover:text-gold"}`}><Icon className="h-4 w-4"/>{id}</button>)}<Link to="/login" className="mt-4 flex items-center gap-3 border-t border-gold/20 px-4 pt-5 text-sm text-ivory/75"><LogOut className="h-4 w-4"/>Logout</Link></aside><main>{active==="Dashboard"&&<Overview/>}{active==="My Orders"&&<Orders/>}{active==="Wishlist"&&<Wishlist/>}{active==="Address Book"&&<Addresses/>}{active==="Account Details"&&<Account/>}</main></div></div>}
function Overview(){return <><h2 className="font-display text-2xl">Welcome back, Sohel</h2><p className="mt-2 text-sm text-muted-foreground">Here is what is happening with your fragrance collection.</p><div className="mt-7 grid gap-4 sm:grid-cols-3">{[["12","Total Orders"],["4","Wishlist Items"],["280","Reward Points"]].map(([n,l])=><div key={l} className="rounded-sm border border-border p-6"><p className="font-display text-3xl text-gold">{n}</p><p className="mt-2 text-xs tracking-wider text-muted-foreground uppercase">{l}</p></div>)}</div><div className="mt-7"><h3 className="font-display text-xl">Recent Orders</h3><OrderTable rows={orders.slice(0,5)}/></div></>}
function Orders(){return <><h2 className="font-display text-2xl">My Orders</h2><OrderTable rows={orders}/></>}
function OrderTable({rows}:{rows:typeof orders}){return <div className="mt-5 overflow-x-auto rounded-sm border border-border"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-off-white text-[10px] tracking-wider text-muted-foreground uppercase"><tr>{["Order ID","Items","Date","Status","Total","Actions"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{rows.map(o=><tr key={o.id} className="border-t border-border"><td className="px-4 py-4 font-medium">{o.id}</td><td className="max-w-52 px-4 py-4 text-muted-foreground">{o.items}</td><td className="px-4 py-4">{o.date}</td><td className="px-4 py-4"><span className={`rounded-sm px-2 py-1 text-[9px] uppercase ${o.status==="Delivered"?"bg-promo text-promo-foreground":o.status==="Shipped"?"bg-accent text-gold":"bg-off-white text-navy"}`}>{o.status}</span></td><td className="px-4 py-4">{formatBDT(o.total)}</td><td className="px-4 py-4"><button className="text-xs text-gold underline">View</button></td></tr>)}</tbody></table></div>}
function Wishlist(){return <><h2 className="font-display text-2xl">Wishlist</h2><div className="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-3">{products.slice(0,3).map(p=><ProductCard key={p.slug} product={p}/>)}</div></>}
function Addresses(){return <><h2 className="font-display text-2xl">Address Book</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-sm border border-gold p-6"><p className="eyebrow">Default address</p><h3 className="mt-3 font-display text-xl">Sohel Rana</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Banani, Dhaka 1213<br/>Bangladesh<br/>+880 1712-345678</p><button className="mt-5 text-xs text-gold underline">Edit</button></div><button onClick={()=>toast.info("Address editor will connect to WooCommerce.")} className="flex min-h-48 flex-col items-center justify-center rounded-sm border border-dashed border-border text-muted-foreground hover:border-gold hover:text-gold"><Plus className="h-6 w-6"/><span className="mt-2 text-xs uppercase">Add New Address</span></button></div></>}
function Account(){return <><h2 className="font-display text-2xl">Account Details</h2><form className="mt-6 max-w-2xl space-y-5 rounded-sm border border-border p-6" onSubmit={e=>{e.preventDefault();toast.success("Account details saved")}}>{["Name","Email","Phone"].map(l=><label key={l} className="block text-xs tracking-wider text-muted-foreground uppercase">{l}<input className="mt-2 w-full rounded-sm border border-input px-4 py-3 text-sm"/></label>)}<h3 className="border-t border-border pt-5 font-display text-xl">Change Password</h3>{["Current Password","New Password"].map(l=><label key={l} className="block text-xs tracking-wider text-muted-foreground uppercase">{l}<input type="password" className="mt-2 w-full rounded-sm border border-input px-4 py-3 text-sm"/></label>)}<button className="rounded-sm bg-promo px-6 py-3 text-xs text-promo-foreground uppercase">Save Changes</button></form></>}